DefiBlog/DefiBlog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DefiBlog/core/urls.py
from django.urls import path, include
from core import views

urlpatterns = [
    path('',views.indexView, name = 'index'),
    path('integrantes/',views.integrantesView, name = 'integrantes'),
    path('publicaciones/', include('publicaciones.urls')),
    path('categorias/', views.categoriasView, name = 'categorias'),
    path('login/', include('usuarios.urls')),
    path('contacto/', include('contacto.urls')) 
]

DefiBlog/publicaciones/urls.py
from django.urls import path
from publicaciones import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'publicaciones'
urlpatterns = [
    path('publicaciones/',views.VerPublicaciones.as_view(), name = 'publicaciones'),
    path('crear-publicacion/', views.CrearPublicacion.as_view(), name='crear-publicacion'),
    path('editar-publicacion/<int:pk>', views.EditarPublicacion.as_view(), name='editar-publicacion'),
    path('eliminar-publicacion/<int:pk>', views.EliminarPublicacion.as_view(), name = 'eliminar-publicacion'),
    path('detalle-post/<int:pk>', views.DetallePublicacion.as_view(), name='detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComentario.as_view(), name='borrar-comentario'),
    path('detalle-post/me_gusta/<int:pk>', views.me_gusta_view, name='me-gusta'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DefiBlog/publicaciones/models.py
from django.db import models
from usuarios.models import usuario


# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre 

class Publicaciones(models.Model):
    fecha = models.DateTimeField(auto_now_add = True)
    update = models.DateTimeField(auto_now=True)
    titulo = models.CharField(max_length = 255)
    post = models.TextField()
    imagen_post = models.ImageField(upload_to='imagenes_post', null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, related_name='posteos', null= True)
    creador = models.ForeignKey(usuario, on_delete=models.CASCADE, related_name='posteos_usario')
    meGusta = models.ManyToManyField(usuario, related_name='publicaciones_gustadas', blank=True)

    def __str__(self):
        return self.titulo + '-' + self.creador.username
    
class Comentario(models.Model):
    texto = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Publicaciones, on_delete=models.CASCADE, related_name='comentarios')
    creador = models.ForeignKey(usuario, on_delete=models.CASCADE, related_name='comentarios')
    meGusta = models.ManyToManyField(usuario, related_name='comentarios_gustados', blank=True)

    def __str__(self):
        return self.post.titulo + '-' + self.creador.username

DefiBlog/publicaciones/forms.py
from django import forms
from .models import Publicaciones, Comentario


class CrearPublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicaciones
        fields = ['categoria', 'titulo', 'post', 'imagen_post']
        labels = {
            'titulo': '',
            'post' : '',
            'categoria' : '',
            'imagen para el post':''
        }
        widgets = {
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Titulo'}),
            'post': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Escriba su post aqui'}),
            'imagen_post': forms.ClearableFileInput(attrs={'class': 'form-control'}), 
        }

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']
        widgets = {
            
            'texto': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Escribe un comentario'}),
        }

DefiBlog/publicaciones/views.py
from typing import Any, Dict
from django.shortcuts import redirect, get_object_or_404, render
from publicaciones.models import Publicaciones, Comentario, Categoria
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse
from .forms import CrearPublicacionForm, ComentarioForm
from django.contrib.auth.mixins import LoginRequiredMixin
from core.mixins import SuperusuarioAutorMixin, ColaboradorMixin
from django.db.models import Count


# Create your views here.
class VerPublicaciones(ListView):
    model = Publicaciones
    template_name = 'publicaciones/publicaciones.html'
    context_object_name = 'posteos'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all
        return context
    
    def get_queryset(self):
        queryset = super().get_queryset()

        # Annotate the queryset with the number of likes for each post
        queryset = queryset.annotate(num_likes=Count('meGusta'))
        
        categoria_seleccionada = self.request.GET.get('categoria')
        queryset = queryset.order_by('-fecha')
        if categoria_seleccionada:
            queryset = queryset.filter(categoria = categoria_seleccionada)
    
        orden = self.request.GET.get('orderby')
        if orden:
            if orden == 'fecha_asc':
                queryset = queryset.order_by('fecha')
            elif orden == 'fecha_desc':
                queryset = queryset.order_by('-fecha')
            elif orden == 'alf_asc':
                queryset = queryset.order_by('titulo')
            elif orden == 'alf_desc':
                queryset = queryset.order_by('-titulo')
            elif orden == 'likes_asc':
                queryset = queryset.order_by('num_likes')
            elif orden == 'likes_desc':
                queryset = queryset.order_by('-num_likes')

        return queryset




class CrearPublicacion(ColaboradorMixin, LoginRequiredMixin, CreateView):
    model = Publicaciones
    template_name = 'publicaciones/crear-publicacion.html'
    form_class = CrearPublicacionForm

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    
    def form_valid(self, form):
            f = form.save(commit=False)
            f.creador_id = self.request.user.id
            return super().form_valid(f)



class EditarPublicacion(SuperusuarioAutorMixin, LoginRequiredMixin, UpdateView):
    model = Publicaciones
    template_name = 'publicaciones/editar-publicacion.html'
    form_class = CrearPublicacionForm

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')


    
class EliminarPublicacion(SuperusuarioAutorMixin, LoginRequiredMixin, DeleteView):
    model = Publicaciones
    template_name ='publicaciones/eliminar-publicacion.html'
    
    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    



class DetallePublicacion(DetailView):
    template_name = 'publicaciones/detalle-publicacion.html'
    model = Publicaciones
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comentario_form'] = ComentarioForm()
        return context
    
    def post(self, request, *args, **kwargs):

        if not self.request.user.is_authenticated:
            return redirect('usuarios:login')

        publicacion = self.get_object()
        form = ComentarioForm(request.POST)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.creador_id = self.request.user.id
            comentario.post = publicacion
            comentario.save()
            return super().get(request)
        else:
            return super().get(request)
        



class BorrarComentario(SuperusuarioAutorMixin, LoginRequiredMixin, DeleteView):
    model = Comentario
    template_name = 'publicaciones/borrar-comentario.html'

    def get_success_url(self):
        return reverse('publicaciones:detalle-post', args = [self.object.post.id])
    



def me_gusta_view(request, pk):
     if request.method == "POST":
         publicacion_id = request.POST.get('publicacion_id')
         publicacion = get_object_or_404(Publicaciones, id = publicacion_id)
         usuario = request.user
         if publicacion.meGusta.filter(id=usuario.id).exists():
             publicacion.meGusta.remove(usuario)
         else:
             publicacion.meGusta.add(usuario)
   
     return redirect('publicaciones:detalle-post' , pk=publicacion_id)

DefiBlog/templates/publicaciones/borrar-comentario.html
{% extends 'base.html' %}

{% block contenido %}

<main class="container text-center">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-5">
    <form method="post" class="card card-body">
      {% csrf_token %}
      <h6>Estas a punto de eliminar el comentario</h6>
      <button type="submit" class="btn btn-danger mt-3">Eliminar</button>
    </form>

  </div>

</main>




{% endblock contenido %}

DefiBlog/templates/publicaciones/crear-publicacion.html
{% extends 'base.html' %} {% block contenido %}

<main class="container text-center">
  <div class="row">
    <div class="col-md-6 offset-md-3 mt-5">
      <div class="card card-body">
        <h5>Nuevo Post</h5>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{form.as_p}}
          <button type="submit" class="btn btn-success">Publicar!</button>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock contenido %}

DefiBlog/templates/publicaciones/detalle-publicacion.html
{% extends 'base.html' %} 

{% block contenido %}

<!-----seccion detalles publicacion------>

<main class="container">
  <section class="container">

        <div class="card">
          <div class="card-body">
            <div class="container text-white bg-dark">
              <p class="card-title">Titulo: {{ post.titulo }}</p>
            </div>
            <p class="card-text">{{post.post}}</p>
          </div>

          {% if post.imagen_post %}
          <img src="{{post.imagen_post.url}}" alt="Imagen del post">
          {% endif %}
            
          
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Publicado: {{post.fecha}}</li>
            <li class="list-group-item">Autor: {{post.creador}}</li>
          </ul>
          <div class="card-body">
            
            {% if user.is_authenticated %}
            <form action="{% url 'publicaciones:me-gusta' post.id %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="publicacion_id" value="{{post.id}}" />
              {% if user in post.meGusta.all %}
              <button type="submit" class="btn btn-success">
                <i class="fa-regular fa-thumbs-up"></i>
              </button>
              {% else %}
              <button type="submit" class="btn">
                <i class="fa-regular fa-thumbs-up"></i>
              </button>
              {% endif %}
            </form>
            {% endif %}
            
          </div>
        </div>


  
    


      </div>
    </div>
  </section>



<!----seccion comentarios----->



  <section class="container">
    
    <div class="col ">

      <div class="card mt-5">
  
        <div class="comentarios-container text-center mt-2">
          <h3>Comentarios</h3>
          <ul class="list-group">
            {% for comentario in post.comentarios.all %}
              <li class="list-group-item list-group-item-info">{{comentario.creador.username}}</li>
              <li class="list-group-item justify-content-between d-flex align-items-center mb-2">{{comentario.texto}} </li>

            {% if user.is_superuser or user == comentario.creador or user == comentario.post.creador%}
              <a href="{% url 'publicaciones:borrar-comentario' comentario.id %}"><i class="fa-solid fa-trash"></i
              ></a>
              {% endif %}
            </li>
        
            {% endfor %}
          </ul>
        </div>
        
        <form method="post">
          {% csrf_token %} {{ comentario_form }}
        
          <button class="btn btn-success" type="submit">Comentar</button>
        </form>
    </div>

    </div>
    

  </section>

  
</main>

{% endblock contenido %}

DefiBlog/templates/publicaciones/editar-publicacion.html
{% extends 'base.html' %}

{% block contenido %}


<main class="container text-center">
  <div class="row">
    <div class="col-md-6 offset-md-3 mt-5">
      <div class=" card card-body">
        <h5>Editar Post</h5>
        <form method="post">
          {% csrf_token %} 
          {{form.as_p}}
          <button type="submit" class="btn btn-success">Guardar Cambios</button>
        </form>
      </div>
    </div>
  </div>
</main>


{% endblock contenido %}

DefiBlog/templates/publicaciones/eliminar-publicacion.html
{% extends 'base.html' %} 

{% block contenido %}

<main class="container text-center">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-5">
    <form method="post" class="card card-body">
      {% csrf_token %}
      <h6>Estas a punto de eliminar la publicacion</h6>
      <button type="submit" class="btn btn-danger mt-3">Eliminar</button>
    </form>

  </div>

</main>

{% endblock contenido %}

DefiBlog/templates/publicaciones/publicaciones.html
{% extends 'base.html' %}

{% load static %} 


{% block contenido %}

<section>
  <div class="caja-publicaciones">
    <div class="container-fluid text-center text-white">
      <h1 class="pb-5 pt-5">SECCION PUBLICACIONES</h1>
      
      <div class="col-md-4 offset-md-4 mt-5">
        
        <form  method="get" class="form ">
          <div class="row justify-content-center">
            <div class="col">
              <select class="form-control mb-4" name="categoria" id="">
                <option value="">Todas</option>
                {% for categoria in categorias %}
                  <option value="{{categoria.id}}" {% if categoria.id|stringformat:"s" == request.GET.categoria %}selected{% endif %}>{{categoria.nombre}}</option>
                {% endfor %}
              </select>
            </div>
        
            <div class="col-xl">
              <select class="form-control mb-2" name="orderby" id="">
                <option value="">Ordenar por</option>
                <option value="fecha_asc" {% if 'fecha_asc' == request.GET.orderby %}selected{% endif %}>Fecha ascendente</option>
                <option value="fecha_desc" {% if 'fecha_desc' == request.GET.orderby %}selected{% endif %}>Fecha descendente</option>
                <option value="alf_asc" {% if 'alf_asc' == request.GET.orderby %}selected{% endif %}>Alfabeticamente ascendente</option>
                <option value="alf_desc" {% if 'alf_desc' == request.GET.orderby %}selected{% endif %}>Alfabeticamente descendente</option>
                <option value="likes_asc" {% if 'likes_asc' == request.GET.orderby %}selected{% endif %}>Menos gustado</option>
                <option value="likes_desc" {% if 'likes_desc' == request.GET.orderby %}selected{% endif %}>Más gustado</option>
              </select>
            </div>
        </form>
        </div>
          <button class="btn btn-success mb-2" type="submit">Filtrar</button>      
        <div>
          {% if user.is_authenticated and user.es_colaborador or user.is_superuser %}
          <a href="{% url 'publicaciones:crear-publicacion' %}" class="btn btn-primary mb-4"
            >Postear algo nuevo!</a
          >
          {% endif %}
    
          </div>
     
      </div>
    </div>
  </div>

</section>


<!--------seccion------>

<div class="container text-center">
  <div class="row justify-content-center">
      {% for post in posteos %}
          <div class="card text-center col-xl-5 col-sm-12 m-2">
            <div class="card-header">
              Autor: {{post.creador}}
            </div>
            <div class="card-body ">
              <h5 class="card-title">{{ post.titulo }}</h5>
              <p class="m-0">Categoría: {{ post.categoria }}</p>
              <!-- Display the number of likes -->
              <p>Likes: {{ post.num_likes }}</p>
              <a href="{% url 'publicaciones:detalle-post' post.id %}"class="btn btn-warning mb-2" >Ver más</a>
              {% if user.is_superuser or user == post.creador %}
                <a href="{% url 'publicaciones:editar-publicacion' post.id %}" class="btn btn-info mb-2">Editar</a>
                <a href="{% url 'publicaciones:eliminar-publicacion' post.id %}" class="btn btn-danger mb-2">Eliminar</a>
              {% endif %}
              <div class="card-footer text-muted">{{ post.fecha }}</div>
            </div>
          </div>
            {% endfor %}
       
    </div>
</div>


<nav class="mt-2" aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
    <a class="page-link"
      href="?page=1{% if request.GET.categoria %}&categoria={{ request.GET.categoria }}{% endif %}{% if request.GET.orderby %}&orderby={{ request.GET.orderby }}{% endif %}"
      ><<</a
    >
  </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.categoria %}&categoria={{ request.GET.categoria }}{% endif %}{% if request.GET.orderby %}&orderby={{ request.GET.orderby }}{% endif %}" tabindex="-1"><</a>
    </li>
    {% endif %}
    
    {% for page_number in page_obj.paginator.page_range %}
      <li class="page-item {% if page_obj.number == page_number %}active{% endif %}">
        <a class="page-link" href="?page={{ page_number }}{% if request.GET.categoria %}&categoria={{ request.GET.categoria }}{% endif %}{% if request.GET.orderby %}&orderby={{ request.GET.orderby }}{% endif %}">{{ page_number }}</a>
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.categoria %}&categoria={{ request.GET.categoria }}{% endif %}{% if request.GET.orderby %}&orderby={{ request.GET.orderby }}{% endif %}">></a>
    </li>
    <li class="page-item">
    <a class="page-link"
      href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.categoria %}&categoria={{ request.GET.categoria }}{% endif %}{% if request.GET.orderby %}&orderby={{ request.GET.orderby }}{% endif %}"
      >>></a
    >
  </li>
    {% endif %}
  </ul>
</nav>

{% endblock contenido %}