DefiBlog/DefiBlog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DefiBlog/contacto/urls.py
from django.urls import path
from .views import ContactoView, mensaje_enviado
app_name = 'contacto'


urlpatterns = [
    path('enviar-mensaje/', ContactoView.as_view(), name='enviar-mensaje'),
    path('mensaje-enviado/', mensaje_enviado, name='mensaje-enviado')
]

DefiBlog/core/urls.py
from django.urls import path, include
from core import views

urlpatterns = [
    path('',views.indexView, name = 'index'),
    path('integrantes/',views.integrantesView, name = 'integrantes'),
    path('publicaciones/', include('publicaciones.urls')),
    path('categorias/', views.categoriasView, name = 'categorias'),
    path('login/', include('usuarios.urls')),
    path('contacto/', include('contacto.urls')) 
]

DefiBlog/publicaciones/urls.py
from django.urls import path
from publicaciones import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'publicaciones'
urlpatterns = [
    path('publicaciones/',views.VerPublicaciones.as_view(), name = 'publicaciones'),
    path('crear-publicacion/', views.CrearPublicacion.as_view(), name='crear-publicacion'),
    path('editar-publicacion/<int:pk>', views.EditarPublicacion.as_view(), name='editar-publicacion'),
    path('eliminar-publicacion/<int:pk>', views.EliminarPublicacion.as_view(), name = 'eliminar-publicacion'),
    path('detalle-post/<int:pk>', views.DetallePublicacion.as_view(), name='detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComentario.as_view(), name='borrar-comentario'),
    path('detalle-post/me_gusta/<int:pk>', views.me_gusta_view, name='me-gusta'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DefiBlog/usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from usuarios.views import RegistroView, LoginView


app_name = 'usuarios'

urlpatterns = [
    path('', LoginView.as_view(template_name = 'usuarios/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(next_page = '../'), name = 'logout'),
    path('registro/', RegistroView.as_view(), name = 'registro' ),
]

DefiBlog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PROYECTO FINAL</title>
    <!-- estilos -->

    <link rel="stylesheet" href="{% static 'css/cssReset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Tektur:wght@500;800&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
    <script
      src="https://kit.fontawesome.com/be59a90cf1.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body id="cuerpo">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand navTextLogo" href="{% url 'index' %}">
          DescentraBlog
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'publicaciones:publicaciones' %}"
                >Publicaciones</a
              >
            </li>
            {% if user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacto:enviar-mensaje' %}"
                >Contacto</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuarios:logout' %}"
                >Cerrar Sesion</a
              >
            </li>
            {% if user.imagen_perfil %}
            <img
              src="{{user.imagen_perfil.url}}"
              alt="imagen de perfil"
              class="rounded-circle"
              width="30"
              height="30"
            />
            </a>

            {% else %}

            <img
              src="{% static 'img/defaultAvatar.png' %}"
              alt="imagen de perfil"
              class="rounded-circle"
              width="30"
              height="30"
            />
            </a>

            {% endif %}
            <li class="nav-item">
              <a class="nav-link">{{user.username}}</a>
            </li>
            

            {% else %}
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'usuarios:login' %}"
              >Iniciar Sesion</a
            >
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'usuarios:registro' %}"
              >Registrarse</a
            >
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block contenido %} {% endblock contenido %}



    <!--------  FOOTER------>

    <div class="container-fluid">
      <footer class="footer bg-dark text-center text-white">
        <div
          class="text-center p"
          style="background-color: rgba(20, 160, 225, 0.695)"
        >
          COMISION 7:
          <a class="text-white" href="{% url 'integrantes' %}">GRUPO 7</a>
        </div>
      </footer>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

DefiBlog/templates/categorias.html
{% extends 'base.html' %} {% load static %} {% block contenido %}
<div class="text-center" id="cuerpointegrantes">
  <h1>CATEGORIAS</h1>
  <div id="integrantes">
    <h2>DEFI</h2>
  </div>
</div>
{% endblock contenido %}

DefiBlog/templates/index.html
{% extends 'base.html' %} 

{% load static %} 

{% block contenido %}

<section>
  <div class="caja-publicaciones">
    <div class="container-fluid text-center text-white">
      
    <div>

      <h2 class="text-center mb-4">Publicaciones destacadas</h2>
      <div class="container text-center mb-2">
        <div class="row justify-content-evenly">
          {% for post in posts %}
          <div class="card text-center col-xl-4 col-sm-12">
            <div class="card-header">Autor: {{post.creador}}</div>
            <div class="card-body">
              <h5 class="card-title">{{ post.titulo }}</h5>
              <p class="m-0">Categoría: {{ post.categoria }}</p>
              <!-- Display the number of likes -->
              <p>Likes: {{ post.num_likes }}</p>
              <a
                href="{% url 'publicaciones:detalle-post' post.id %}"
                class="btn btn-warning mb-2"
                >Ver más</a
              >
              {% if user.is_superuser or user == post.creador %}
              <a
                href="{% url 'publicaciones:editar-publicacion' post.id %}"
                class="btn btn-info mb-2"
                >Editar</a
              >
              <a
                href="{% url 'publicaciones:eliminar-publicacion' post.id %}"
                class="btn btn-danger mb-2"
                >Eliminar</a
              >
              {% endif %}
              <div class="card-footer text-muted">{{ post.fecha }}</div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      
      <div class="container mb-4">
        <div class="row justify-content-center">
          <div class="col-12">
            <ul class="list-group">
              <li class="list-group-item">
                Las Finanzas Descentralizadas, también conocidas como DeFi
                (Decentralized Finance en inglés), son una innovadora y revolucionaria
                tendencia en el mundo financiero que se basa en la tecnología de
                blockchain y criptomonedas para ofrecer servicios financieros de
                manera descentralizada y sin intermediarios.
              </li>
              <li class="list-group-item">
                En el ecosistema de DeFi, se utilizan contratos inteligentes para
                crear protocolos y aplicaciones que permiten a los usuarios acceder a
                una amplia gama de servicios financieros, como préstamos,
                intercambios, pagos, seguros y más
              </li>
              <li class="list-group-item">
                Estos protocolos son impulsados por la comunidad y operan en redes
                públicas de blockchain, lo que significa que cualquier persona puede
                participar y beneficiarse de ellos sin necesidad de intermediarios
          tradicionales como bancos u otras instituciones financieras.
        </li>
        <li class="list-group-item">
          Una de las principales características de las Finanzas
          Descentralizadas es que son abiertas y transparentes. Toda la
          actividad y los fondos se registran en la cadena de bloques, lo que
          brinda una mayor seguridad y confianza a los usuarios. Además, las
          transacciones son rápidas y pueden realizarse en cualquier momento, ya
          que la red blockchain está disponible las 24 horas del día, los 7 días
          de la semana.
        </li>
        <li class="list-group-item">
          Otro aspecto destacado de DeFi es que es inclusivo. Permite que
          personas de todo el mundo, incluso aquellas que no tienen acceso a
          servicios financieros tradicionales, puedan participar en la economía
          global y acceder a productos financieros avanzados. Sin embargo, como
          con cualquier tecnología emergente, las Finanzas Descentralizadas
          también enfrentan desafíos y riesgos. La seguridad de los contratos
          inteligentes y la protección de los fondos son aspectos críticos que
          deben abordarse adecuadamente. Además, la regulación en torno a DeFi
          todavía no está completamente definida, lo que puede plantear
          incertidumbre en algunos casos. En general, las Finanzas
          Descentralizadas están transformando la forma en que entendemos y
          participamos en el sistema financiero global. Su potencial para
          brindar acceso financiero, eliminar intermediarios y promover la
          inclusión financiera hace que sean una tendencia emocionante y
          prometedora para el futuro. Sin embargo, como usuario potencial de
          DeFi, es esencial comprender los riesgos asociados y adoptar buenas
          prácticas de seguridad para proteger los activos digitales.
        </li>
      </ul>
    </div>
  </div>
</div>
</section>

{% endblock contenido %}

DefiBlog/templates/integrantes.html
{% extends 'base.html' %} {% load static %} {% block contenido %}
<div class="text-center" id="cuerpointegrantes">
  <h1>INTEGRANTES DEL GRUPO 7</h1>
  <div id="integrantes">
    <p>ELIAS BRAZANOVICH</p>
    <p>MAURICIO STALCAR</p>
    <p>ALBERTO FABIAN BASTIANI</p>
    <p>NICOLAS MIGUEL ARREJIN</p>
    <p>AGUSTIN RODRIGUEZ</p>
  </div>
</div>
{% endblock contenido %}